# Generated by Django 6.0.5 on 2026-06-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_alter_auction_starting_price_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("active", "Active"),
                    ("ended", "Ended"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
    ]
